language: python

python:
  - "2.6"
  - "2.7"

install:
    pip install coveralls --use-mirrors

script:
    coverage run --source=eclipsescraper setup.py test

after_success:
    coveralls

notifications:
  email:
    - frencils@gmail.com