language: python

python:
  - "3.3"
  - "3.4"

install:
    pip install coveralls --use-mirrors

script:
    coverage run --source=eclipsescraper setup.py test

after_success:
    coveralls

notifications:
  email:
    - frencils@gmail.com